[package]
name = "mvv_account_web"
version = "0.1.0"
edition = "2021"

[dependencies]
unknown_dep = "678"

[package.metadata.patch-replace-sub-dependencies.progenitor-client]
replace = [
    { sub_dep = "reqwest", from_ver = "0.11.27", to_ver = "0.12.5" },
]
