
[build-dependencies]
progenitor = "0.7.0"
cargo-progenitor = "0.7.0"


[dependencies]
reqwest = { version = "0.12.5", features = ["default", "json", "stream"] }


[dependencies.progenitor-client]
version = "0.7.0"
features = []


[dev-dependencies]
